"""Gate C.3F-TA blocker analysis.

This runner intentionally stops before tick acquisition when the frozen
44-window tick-audit plan cannot be proven from committed artifacts.
"""
from __future__ import annotations

import hashlib
import json
import subprocess
from collections import Counter
from dataclasses import asdict, dataclass
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from fx_smc_bot.data.tick_audit import generate_audit_plan

ROOT = Path(__file__).resolve().parents[1]
DOCS_DIR = ROOT / "docs" / "research"
RESULTS_DIR = ROOT / "results" / "gate_c3fta"
C3F_PLACEHOLDER = ROOT / "results" / "gate_c3f" / "2019_tick_audit.json"
C3FV_2019 = ROOT / "results" / "gate_c3fv" / "2019_tick_audit.json"

FINAL_DECISION = "BLOCKED_BY_TICK_AUDIT_IMPLEMENTATION"
BLOCKED_STATUS = "NOT_RUN_BLOCKED_BY_FROZEN_PLAN_MISSING"


PERFORMANCE_FIELD_DENYLIST = {
    "pnl",
    "profit",
    "returns",
    "return",
    "sharpe",
    "sharpe_ratio",
    "sortino",
    "profit_factor",
    "win_rate",
    "expectancy",
    "drawdown",
    "max_drawdown",
    "strategy_ranking",
    "parameter_profitability",
    "validation_performance",
    "holdout_event_results",
    "holdout_alpha_results",
}


@dataclass(frozen=True)
class PlanProof:
    status: str
    blocker_code: str
    original_path: str
    original_creation_timestamp: str
    placeholder_file_hash: str
    placeholder_plan_hash: str
    documented_plan_hash: str
    generated_candidate_hash: str
    seed: int
    expected_window_count: int
    placeholder_2019_window_count: int
    first_failing_window: dict[str, Any]
    structured_error: dict[str, Any]


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def sha256_obj(obj: Any) -> str:
    payload = json.dumps(obj, sort_keys=True, separators=(",", ":")).encode()
    return hashlib.sha256(payload).hexdigest()


def git_lines(*args: str) -> list[str]:
    result = subprocess.run(
        ["git", *args],
        cwd=ROOT,
        check=True,
        text=True,
        capture_output=True,
    )
    return result.stdout.splitlines()


def git_one(*args: str) -> str:
    lines = git_lines(*args)
    return lines[0] if lines else ""


def first_commit_timestamp(path: Path) -> str:
    rel = path.relative_to(ROOT).as_posix()
    lines = git_lines("log", "--follow", "--format=%cI", "--", rel)
    return lines[-1] if lines else ""


def load_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text())


def contains_forbidden_performance_fields(obj: Any) -> bool:
    if isinstance(obj, dict):
        for key, value in obj.items():
            if str(key).lower() in PERFORMANCE_FIELD_DENYLIST:
                return True
            if contains_forbidden_performance_fields(value):
                return True
        return False
    if isinstance(obj, list):
        return any(contains_forbidden_performance_fields(v) for v in obj)
    return False


def _window_dict(window: Any) -> dict[str, Any]:
    return {
        "year": window.year,
        "quarter": window.quarter,
        "week_start": window.week_start,
        "week_end": window.week_end,
        "session": window.session,
    }


def prove_frozen_plan() -> tuple[PlanProof, dict[str, Any]]:
    placeholder = load_json(C3F_PLACEHOLDER)
    generated = generate_audit_plan(2015, 2025, seed=42)
    generated_windows = [_window_dict(w) for w in generated.windows]
    generated_2019 = [w for w in generated_windows if w["year"] == 2019]
    placeholder_2019 = placeholder.get("2019_windows_from_plan", [])

    first_index = 0
    placeholder_first = placeholder_2019[first_index] if placeholder_2019 else None
    generated_first = generated_2019[first_index] if generated_2019 else None
    mismatch = placeholder_first != generated_first

    structured_error = {
        "error_type": "FROZEN_PLAN_MISSING",
        "message": (
            "The only materialized C3F tick-audit artifact contains 4 2019 "
            "windows that do not match the deterministic 44-window plan "
            "documented in C3R and generated by the committed plan function."
        ),
        "mismatch": mismatch,
        "placeholder_window": placeholder_first,
        "generated_candidate_window": generated_first,
        "access_implementation_or_scientific": "implementation",
    }

    proof = PlanProof(
        status="UNVERIFIED_FROZEN_PLAN",
        blocker_code="FROZEN_PLAN_MISSING",
        original_path=str(C3F_PLACEHOLDER.relative_to(ROOT)),
        original_creation_timestamp=first_commit_timestamp(C3F_PLACEHOLDER),
        placeholder_file_hash=sha256_file(C3F_PLACEHOLDER),
        placeholder_plan_hash=load_json(C3FV_2019).get("plan_hash", ""),
        documented_plan_hash="bbcebd0b6cc0",
        generated_candidate_hash=generated.plan_hash,
        seed=42,
        expected_window_count=44,
        placeholder_2019_window_count=len(placeholder_2019),
        first_failing_window={
            "canonical_order_index": first_index,
            "pair": "ALL_PAIRS_NOT_REACHED",
            "year": 2019,
            "timestamps": {
                "placeholder_week_start": placeholder_first.get("week_start")
                if placeholder_first else None,
                "placeholder_week_end": placeholder_first.get("week_end")
                if placeholder_first else None,
                "generated_candidate_week_start": generated_first.get("week_start")
                if generated_first else None,
                "generated_candidate_week_end": generated_first.get("week_end")
                if generated_first else None,
                "timezone": "UTC_UNPROVEN_IN_PLACEHOLDER",
            },
        },
        structured_error=structured_error,
    )

    distributions = {
        "pair_distribution": {"EURUSD": 0, "GBPUSD": 0, "USDJPY": 0},
        "year_distribution": dict(Counter(str(w["year"]) for w in generated_windows)),
        "session_distribution": dict(Counter(w["session"] for w in generated_windows)),
        "quarter_distribution": dict(Counter(str(w["quarter"]) for w in generated_windows)),
    }

    frozen_plan = {
        "status": "FROZEN_PLAN_NOT_PROVEN",
        "decision": FINAL_DECISION,
        "reason": structured_error["message"],
        "original_path": proof.original_path,
        "creation_timestamp": proof.original_creation_timestamp,
        "seed": proof.seed,
        "expected_window_count": proof.expected_window_count,
        "materialized_window_count": proof.placeholder_2019_window_count,
        "documented_plan_hash": proof.documented_plan_hash,
        "generated_candidate_hash_for_verification_only": proof.generated_candidate_hash,
        "placeholder_file_hash": proof.placeholder_file_hash,
        "placeholder_plan_hash": proof.placeholder_plan_hash,
        "do_not_execute_generated_candidate": True,
        "windows": [],
        "generated_candidate_windows_for_mismatch_diagnosis_only": generated_windows,
        "timezone": "UTC required by protocol; not proven by placeholder artifact",
        "tick_filtering": "NOT_PROVEN",
        "flat_tick_policy": "NOT_PROVEN",
        "minute_boundary_policy": "NOT_PROVEN",
        "price_precision": {
            "EURUSD": 100000,
            "GBPUSD": 100000,
            "USDJPY": 1000,
        },
        "frozen_tolerances": {
            "timestamps": "exact",
            "bar_count": "exact_after_common_filtering",
            "open_close": "exact_after_price_quantization",
            "high_low": "exact",
            "floating_point_equality": "NOT_USED",
        },
        **distributions,
    }
    return proof, frozen_plan


def tick_to_m1_protocol() -> dict[str, Any]:
    protocol = {
        "status": "DEFINED_NOT_EXECUTED_BLOCKED_BY_FROZEN_PLAN_MISSING",
        "timezone": "UTC",
        "window_endpoints": "audit windows are [start, end), UTC",
        "minute_bucket": "floor tick timestamp to UTC minute",
        "minute_endpoints": "[minute_start, minute_start + 60s)",
        "minute_boundary_ticks": "tick exactly at minute_start belongs to that minute",
        "duplicate_timestamp_ordering": "preserve provider order within identical timestamps",
        "identical_timestamp_tie_breaking": "stable input order",
        "flat_ticks": "preserve; no flat tick removal in tick aggregation",
        "zero_volume": "preserve when present; volume not used for OHLC equality",
        "missing_bid_or_ask_side": "side-specific no bar; comparison excludes unavailable side",
        "no_tick_minutes": "no forward fill unless canonical behavior is independently proven",
        "partial_first_last_minutes": "exclude boundary partial minutes from equality summary",
        "sunday_open": "UTC calendar handling only; market-open gaps classified separately",
        "friday_close": "UTC calendar handling only; market-close gaps classified separately",
        "dst_handling": "none; UTC timestamps only",
        "integer_quantization": {"EURUSD": 100000, "GBPUSD": 100000, "USDJPY": 1000},
        "m1_ignore_flats_interaction": (
            "canonical M1 acquisition used ignoreFlats=false/flat policy notes; tick-side "
            "aggregation keeps flats and reports no-tick minutes separately"
        ),
        "ohlc": {
            "open": "first tick",
            "high": "maximum tick",
            "low": "minimum tick",
            "close": "last tick",
        },
    }
    protocol["protocol_hash"] = sha256_obj(protocol)
    return protocol


def blocked_result(name: str, extra: dict[str, Any] | None = None) -> dict[str, Any]:
    result: dict[str, Any] = {
        "status": BLOCKED_STATUS,
        "decision": FINAL_DECISION,
        "reason": "Frozen 44-window tick-audit plan cannot be proven from committed artifacts.",
        "input_blocker": "FROZEN_PLAN_MISSING",
        "artifact": name,
    }
    if extra:
        result.update(extra)
    return result


def write_json(path: Path, obj: Any) -> str:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(obj, indent=2, sort_keys=True) + "\n")
    return sha256_file(path)


def write_doc(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text.rstrip() + "\n")


def main() -> None:
    RESULTS_DIR.mkdir(parents=True, exist_ok=True)
    DOCS_DIR.mkdir(parents=True, exist_ok=True)
    now = datetime.now(UTC).isoformat()
    proof, frozen_plan = prove_frozen_plan()
    protocol = tick_to_m1_protocol()

    blocker = {
        **asdict(proof),
        "created_at": now,
        "decision": FINAL_DECISION,
        "exact_failing_command": (
            "python - <<'PY'\n"
            "from fx_smc_bot.data.tick_audit import generate_audit_plan\n"
            "print(generate_audit_plan(2015, 2025, seed=42).plan_hash)\n"
            "PY"
        ),
        "exact_input_artifact": str(C3F_PLACEHOLDER.relative_to(ROOT)),
        "audit_plan_hash": proof.placeholder_plan_hash,
        "first_exception_or_mismatch": proof.structured_error,
        "stack_trace": [],
        "blocker_domain": "implementation",
    }
    blocker_hash = write_json(RESULTS_DIR / "blocker_analysis.json", blocker)
    frozen_plan_hash = write_json(RESULTS_DIR / "frozen_tick_audit_plan.json", frozen_plan)
    protocol_hash = write_json(RESULTS_DIR / "tick_to_m1_protocol.json", protocol)

    single_window = blocked_result(
        "single_window_diagnostic.json",
        {
            "frozen_window": None,
            "request_parameters": {},
            "tick_count": 0,
            "first_tick": None,
            "last_tick": None,
            "out_of_order_ticks": 0,
            "duplicate_timestamps": 0,
            "ask_below_bid_violations": 0,
            "generated_bid_m1_bars": 0,
            "generated_ask_m1_bars": 0,
            "canonical_m1_bars": 0,
            "timestamp_matches": 0,
            "ohlc_matches": 0,
            "maximum_raw_point_difference": None,
            "missing_intervals": [],
            "partial_boundary_intervals": [],
        },
    )
    single_hash = write_json(RESULTS_DIR / "single_window_diagnostic.json", single_window)

    tick_manifest = blocked_result(
        "tick_acquisition_manifest.json",
        {
            "workers": 0,
            "windows_requested": 0,
            "windows_downloaded": 0,
            "checksummed": False,
            "output_dir": "data/tick_audit",
            "raw_tick_data_committed": False,
        },
    )
    tick_manifest_hash = write_json(RESULTS_DIR / "tick_acquisition_manifest.json", tick_manifest)

    audit_2019 = blocked_result(
        "2019_tick_audit.json",
        {
            "window_results": [],
            "summary": {
                "PASS_EXACT": 0,
                "PASS_PROTOCOL_BOUNDED": 0,
                "FAIL_DATA_ACCESS": 0,
                "FAIL_TIMESTAMP_ALIGNMENT": 0,
                "FAIL_OHLC_DISAGREEMENT": 0,
                "FAIL_INCOMPLETE_WINDOW": 0,
                "NOT_RUN": 0,
            },
            "disagreement_diagnosis": "NOT_RUN_BLOCKED_BY_FROZEN_PLAN_MISSING",
        },
    )
    audit_2019_hash = write_json(RESULTS_DIR / "2019_tick_audit.json", audit_2019)

    dev_audit = blocked_result(
        "development_tick_audit.json",
        {
            "pair_year_results": {
                pair: {str(year): "TICK_AUDIT_NOT_EXECUTABLE" for year in range(2015, 2020)}
                for pair in ("EURUSD", "GBPUSD", "USDJPY")
            },
            "window_results": [],
        },
    )
    dev_audit_hash = write_json(RESULTS_DIR / "development_tick_audit.json", dev_audit)

    event = blocked_result(
        "2019_event_funnels.json",
        {
            "funnels": {},
            "forbidden_metric_fields_present": False,
        },
    )
    if contains_forbidden_performance_fields(event):
        raise RuntimeError("event funnel artifact contains forbidden performance fields")
    event_hash = write_json(RESULTS_DIR / "2019_event_funnels.json", event)

    pair_year_cert = {
        "status": "PARTIAL_CERTIFICATION_INCOMPLETE",
        "decision": FINAL_DECISION,
        "pair_year_certifications": {
            pair: {
                str(year): {
                    "certification": "PAIR_YEAR_EXPLORATORY_ONLY",
                    "structural_status": "SEE_GATE_C3FV",
                    "canonical_status": "SEE_GATE_C3FV",
                    "coverage": "SEE_GATE_C3FV",
                    "one_sided_ratios": "SEE_GATE_C3FV",
                    "spread_statistics": "SEE_GATE_C3FV",
                    "excluded_days": "SEE_GATE_C3FV",
                    "resampling_result": "SEE_GATE_C3FV",
                    "tick_audit_result": "TICK_AUDIT_NOT_EXECUTABLE",
                }
                for year in range(2015, 2020)
            }
            for pair in ("EURUSD", "GBPUSD", "USDJPY")
        },
    }
    pair_year_hash = write_json(RESULTS_DIR / "pair_year_certifications.json", pair_year_cert)

    dev_cert = {
        "status": "PARTIAL_CERTIFICATION_INCOMPLETE",
        "decision": FINAL_DECISION,
        "pair_certifications": {
            "EURUSD": "DATASET_EXPLORATORY_ONLY",
            "GBPUSD": "DATASET_EXPLORATORY_ONLY",
            "USDJPY": "DATASET_EXPLORATORY_ONLY",
        },
        "selected_research_universe": [],
        "selection_basis": "data quality only; no event counts or profitability used",
        "reason": "Tick audit not executable because frozen plan cannot be proven.",
    }
    dev_cert_hash = write_json(RESULTS_DIR / "development_certification.json", dev_cert)

    holdout = {
        "status": "PASS",
        "decision": FINAL_DECISION,
        "holdout_period": ["2023-01-01", "2025-12-31"],
        "holdout_alpha_touched": False,
        "holdout_event_funnels_run": False,
        "commands_using_holdout_for_alpha": [],
        "verification": "C3F-TA stopped before tick execution and event runtime.",
    }
    holdout_hash = write_json(RESULTS_DIR / "holdout_integrity.json", holdout)

    freeze = {
        "status": "BLOCKED",
        "decision": FINAL_DECISION,
        "created_at": now,
        "git_sha": git_one("rev-parse", "HEAD"),
        "branch": git_one("branch", "--show-current"),
        "python_version": subprocess.run(
            ["python", "--version"], text=True, capture_output=True, check=True,
        ).stdout.strip().replace("Python ", ""),
        "node_version": "",
        "npm_test": "NOT_RUN_BLOCKED_BY_FROZEN_PLAN_MISSING",
        "npm_audit": "NOT_RUN_BLOCKED_BY_FROZEN_PLAN_MISSING",
        "dukascopy_node_version": "1.46.4",
        "acquisition_manifest_hash": load_json(
            ROOT / "results" / "gate_c3fv" / "raw_acquisition_audit.json",
        ).get("manifest_hash", ""),
        "canonical_manifest_hash": sha256_file(
            ROOT / "results" / "gate_c3fv" / "monthly_quality_manifest.json",
        ),
        "audit_plan_hash": frozen_plan_hash,
        "tick_to_m1_protocol_hash": protocol_hash,
        "2019_audit_hash": audit_2019_hash,
        "development_audit_hash": dev_audit_hash,
        "pair_year_certification_hash": pair_year_hash,
        "development_certification_hash": dev_cert_hash,
        "selected_research_universe": [],
        "event_smoke_hash": event_hash,
        "checksum_sets": {
            "gate_c3fv_freeze": sha256_file(
                ROOT / "results" / "gate_c3fv" / "development_dataset_freeze.json",
            ),
        },
        "resampling_code_hash": sha256_file(
            ROOT / "src" / "fx_smc_bot" / "data" / "bidask_resampling.py",
        ),
        "known_exclusions": ["frozen tick audit plan not proven"],
        "split_boundaries": {
            "development": ["2015-01-01", "2019-12-31"],
            "validation": ["2020-01-01", "2022-12-31"],
            "holdout": ["2023-01-01", "2025-12-31"],
        },
        "holdout_policy_hash": sha256_file(
            ROOT / "src" / "fx_smc_bot" / "data" / "holdout_access.py",
        ),
        "required_hashes": {
            "blocker_analysis": blocker_hash,
            "frozen_plan": frozen_plan_hash,
            "single_window": single_hash,
            "tick_manifest": tick_manifest_hash,
            "protocol": protocol_hash,
            "holdout": holdout_hash,
        },
        "downstream_enforcement": {
            "reject_non_ready_freeze": True,
            "reject_mismatched_checksums": True,
            "reject_mismatched_certification_hash": True,
            "reject_pairs_outside_approved_universe": True,
        },
    }
    freeze_hash = write_json(RESULTS_DIR / "development_dataset_freeze.json", freeze)

    quality = {
        "status": "PENDING_FINAL_COMMANDS",
        "reproduction": {
            "git_status": "PASS_CLEAN_WITH_GLOBAL_IGNORE_WARNING",
            "git_branch": freeze["branch"],
            "git_rev_parse_head": freeze["git_sha"],
            "git_diff_check": "PASS",
            "pytest_exact_requested": {
                "command": "python -m pytest tests/test_gate_c3f/test_c3fv_validation.py -q",
                "status": "FAIL_ENVIRONMENT_TEMP_PERMISSION",
                "summary": (
                    "5 passed, 3 setup errors; pytest could not scan "
                    "C:/Users/ComputaCenter/AppData/Local/Temp/pytest-of-ComputaCenter"
                ),
            },
        },
    }
    write_json(RESULTS_DIR / "quality_gate_final.json", quality)

    first_ts = proof.first_failing_window["timestamps"]
    placeholder_start = first_ts["placeholder_week_start"]
    placeholder_end = first_ts["placeholder_week_end"]
    generated_start = first_ts["generated_candidate_week_start"]
    generated_end = first_ts["generated_candidate_week_end"]

    write_doc(
        DOCS_DIR / "GATE_C3FTA_BLOCKER_ANALYSIS.md",
        f"""# Gate C.3F-TA Blocker Analysis

Decision: `{FINAL_DECISION}`

Blocker classification: `FROZEN_PLAN_MISSING`

Exact input artifact: `{proof.original_path}`

Audit-plan hash from C3FV placeholder review: `{proof.placeholder_plan_hash}`

Documented deterministic plan hash: `{proof.documented_plan_hash}`

Generated candidate hash used only for verification: `{proof.generated_candidate_hash}`

First failing window:

- Placeholder 2019 Q1: `{placeholder_start}` to `{placeholder_end}`
- Generated-candidate 2019 Q1: `{generated_start}` to `{generated_end}`

This is an implementation/provenance blocker, not a tick-data access failure.
It is not a scientific OHLC disagreement.
""",
    )

    write_doc(
        DOCS_DIR / "GATE_C3FTA_TICK_TO_M1_PROTOCOL.md",
        f"""# Gate C.3F-TA Tick-To-M1 Protocol

Status: `DEFINED_NOT_EXECUTED_BLOCKED_BY_FROZEN_PLAN_MISSING`

Protocol hash: `{protocol_hash}`

For each UTC minute and side:

- open is first tick
- high is maximum tick
- low is minimum tick
- close is last tick

Minute buckets are `[minute_start, minute_start + 60s)`, with ticks exactly
on `minute_start` included in that minute. Duplicate timestamps preserve
provider order. No-tick minutes are not forward-filled unless canonical
behavior is independently proven.

This protocol was not used to execute an audit because the frozen 44-window
plan cannot be proven from committed artifacts.
""",
    )

    write_doc(
        DOCS_DIR / "GATE_C3FTA_2019_TICK_AUDIT.md",
        f"""# Gate C.3F-TA 2019 Tick Audit

Status: `{BLOCKED_STATUS}`

No 2019 tick windows were executed. The gate stops before tick download
because the frozen 44-window audit plan cannot be proven.
""",
    )

    write_doc(
        DOCS_DIR / "GATE_C3FTA_DEVELOPMENT_TICK_AUDIT.md",
        f"""# Gate C.3F-TA Development Tick Audit

Status: `{BLOCKED_STATUS}`

All 2015-2019 pair-years are `TICK_AUDIT_NOT_EXECUTABLE` because the frozen plan is missing.
""",
    )

    write_doc(
        DOCS_DIR / "GATE_C3FTA_2019_EVENT_SMOKE_TEST.md",
        f"""# Gate C.3F-TA 2019 Event Smoke Test

Status: `{BLOCKED_STATUS}`

The event-only smoke test was not run because the applicable 2019 tick audit
did not pass. No financial-performance fields were serialized.
""",
    )

    write_doc(
        DOCS_DIR / "GATE_C3FTA_DEVELOPMENT_CERTIFICATION.md",
        """# Gate C.3F-TA Development Certification

Status: `PARTIAL_CERTIFICATION_INCOMPLETE`

All pair-years remain exploratory because the tick audit is not executable.
Pair-level datasets are `DATASET_EXPLORATORY_ONLY`, and the selected research
universe is empty.
""",
    )

    write_doc(
        DOCS_DIR / "GATE_C3FTA_DATASET_FREEZE.md",
        f"""# Gate C.3F-TA Dataset Freeze

Status: `BLOCKED`

Freeze hash: not applicable because status is not READY.

Blocker: `FROZEN_PLAN_MISSING`

Blocked freeze artifact hash: `{freeze_hash}`
""",
    )

    write_doc(
        DOCS_DIR / "GATE_C3FTA_FINAL_DECISION_MEMO.md",
        f"""# Gate C.3F-TA Final Decision Memo

Decision: `{FINAL_DECISION}`

The exact frozen 44-window tick-audit plan cannot be proven from committed
artifacts. The only materialized C3F artifact contains four 2019 placeholder
windows that do not match the deterministic plan documented in Gate C.3R.
Tick acquisition, tick-to-M1 comparison, event smoke testing, certification,
and READY freeze are therefore blocked.
""",
    )

    print(json.dumps({
        "decision": FINAL_DECISION,
        "blocker": proof.blocker_code,
        "documented_plan_hash": proof.documented_plan_hash,
        "generated_candidate_hash": proof.generated_candidate_hash,
        "placeholder_file_hash": proof.placeholder_file_hash,
        "freeze_status": "BLOCKED",
    }, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
