from __future__ import annotations

import json
import subprocess
import sys
import uuid
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[2]
SCRIPT = ROOT / "scripts" / "run_gate_f0rpe2erusdsrlpaeursr_eur.py"
RESULTS = ROOT / "results" / "gate_f0rpe2erusdsrlpaeursr"
EXTERNAL_TMP = ROOT.parent / "FX-smc-bot-local-data" / "test-tmp"


def test_runner_dry_run_is_offline_and_does_not_create_database() -> None:
    external_root = EXTERNAL_TMP / f"eur-v4-{uuid.uuid4().hex}"
    database = external_root / "rate-vintage-v4.sqlite3"
    completed = subprocess.run(
        [
            sys.executable,
            str(SCRIPT),
            "--source-clean-room-root",
            str(external_root / "source"),
            "--v4-database",
            str(database),
            "--retrieved-at",
            "2026-08-01T11:38:00+00:00",
            "--dry-run",
        ],
        cwd=ROOT,
        check=True,
        capture_output=True,
        text=True,
    )

    result = json.loads(completed.stdout)
    assert result["status"] == "DRY_RUN"
    assert result["request_count"] == 3
    assert result["network_request_count"] == 0
    assert result["parse_count"] == 0
    assert result["v4_database_created"] is False
    assert not database.exists()


def test_runner_rejects_a_database_inside_git() -> None:
    completed = subprocess.run(
        [
            sys.executable,
            str(SCRIPT),
            "--source-clean-room-root",
            str(EXTERNAL_TMP / f"eur-source-{uuid.uuid4().hex}"),
            "--v4-database",
            str(ROOT / "forbidden-eur-rate-vintage-v4.sqlite3"),
            "--retrieved-at",
            "2026-08-01T11:38:00+00:00",
            "--dry-run",
        ],
        cwd=ROOT,
        check=False,
        capture_output=True,
        text=True,
    )

    assert completed.returncode != 0
    assert "V4_DATABASE_MUST_BE_OUTSIDE_GIT" in completed.stderr
    assert not (ROOT / "forbidden-eur-rate-vintage-v4.sqlite3").exists()


def test_runner_contains_no_network_client_or_late_year_literals() -> None:
    source = SCRIPT.read_text(encoding="utf-8")

    assert "OfficialRateSnapshotClient" not in source
    assert "urlopen" not in source
    assert "requests." not in source
    assert "2023" not in source
    assert "2024" not in source
    assert "2025" not in source


def test_eur_certification_artifacts_pass_and_contain_no_official_rows() -> None:
    if not (RESULTS / "eur_adapter_v3_certification.json").exists():
        pytest.skip("EUR certification artifacts are generated by the live clean-room run")
    adapter = json.loads((RESULTS / "eur_adapter_v3_certification.json").read_text())
    store = json.loads((RESULTS / "eur_vintage_store_certification.json").read_text())
    asof = json.loads((RESULTS / "eur_asof_availability_audit.json").read_text())
    transition = json.loads((RESULTS / "eonia_estr_transition_audit.json").read_text())

    assert adapter["status"] == store["status"] == asof["status"] == "PASS"
    assert transition["status"] == "PASS"
    assert adapter["request_count"] == adapter["snapshot_count"] == 3
    assert adapter["eonia_version_count"] == 8
    assert adapter["estr_version_count"] == 4
    assert asof["asof_before_availability_missing"] == 12
    assert asof["asof_at_availability_available"] == 12
    assert asof["asof_after_availability_available"] == 12
    assert transition["last_primary_eonia_observation"] == "2019-09-30"
    assert transition["first_primary_estr_observation"] == "2019-10-01"

    serialized = json.dumps([adapter, store, asof, transition], sort_keys=True)
    for forbidden in ('"value"', "refRates", "percentRate", "effectiveDate"):
        assert forbidden not in serialized
