from __future__ import annotations

import json
import subprocess
import sys
import uuid
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[2]
SCRIPT = ROOT / "scripts" / "run_gate_f0rpe2erusdsrlpaeursr_live_adapters.py"
RESULTS = ROOT / "results" / "gate_f0rpe2erusdsrlpaeursr"
EXTERNAL_TMP = ROOT.parent / "FX-smc-bot-local-data" / "test-tmp"


def test_live_runner_dry_run_starts_after_usd_and_eur_precertification() -> None:
    completed = subprocess.run(
        [
            sys.executable,
            str(SCRIPT),
            "--clean-room-root",
            str(EXTERNAL_TMP / f"live-{uuid.uuid4().hex}"),
            "--dry-run",
        ],
        cwd=ROOT,
        check=True,
        capture_output=True,
        text=True,
    )

    result = json.loads(completed.stdout)
    assert result["status"] == "DRY_RUN"
    assert result["precertified_official_request_count"] == 5
    assert result["remaining_official_rate_provider_requests_sent"] == 0
    assert result["market_provider_requests_sent"] == 0
    assert {item["currency"] for item in result["request_windows"]} == {
        "GBP",
        "AUD",
        "JPY",
        "CAD",
        "CHF",
    }


def test_live_runner_rejects_clean_room_inside_git() -> None:
    completed = subprocess.run(
        [
            sys.executable,
            str(SCRIPT),
            "--clean-room-root",
            str(ROOT / "forbidden-clean-room"),
            "--dry-run",
        ],
        cwd=ROOT,
        check=False,
        capture_output=True,
        text=True,
    )

    assert completed.returncode != 0
    assert "CLEAN_ROOM_ROOT_MUST_BE_OUTSIDE_GIT" in completed.stderr


def test_live_runner_does_not_reactivate_eur_v2_or_invalid_eon_key() -> None:
    source = SCRIPT.read_text(encoding="utf-8")

    assert "EcbEoniaEstrAdapterV2" not in source
    assert "ECB_EONIA_ESTR_V2" not in source
    assert "EON.B.EU000A2X2A25.WT" not in source
    assert "2023" not in source
    assert "2024" not in source
    assert "2025" not in source


def test_live_adapter_artifacts_preserve_usd_eur_and_block_market_access() -> None:
    if not (RESULTS / "live_adapter_certification.json").exists():
        pytest.skip("live adapter artifacts are generated by the bounded live run")
    certification = json.loads(
        (RESULTS / "live_adapter_certification.json").read_text()
    )
    matrix = json.loads((RESULTS / "live_adapter_matrix.json").read_text())

    assert certification["status"] in {"PASS", "FAIL"}
    assert certification["adapter_certifications"]["USD"]["status"] == "PASS"
    assert certification["adapter_certifications"]["EUR"]["status"] == "PASS"
    assert matrix["adapters"]["EUR"]["adapter_id"] == "ECB_EONIA_ESTR_V3"
    assert matrix["invalid_eon_key_active"] is False
    assert certification["market_provider_requests_sent"] == 0
    assert certification["numerical_rows_exposed_to_parser"] == 0
